name: Deno Deploy

on:
  push:
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Cache Deno directories
        uses: actions/cache@v3
        id: deno-cache
        with:
          path: |
            /opt/hostedtoolcache/deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        if: steps.deno-cache.outputs.cache-hit != 'true'
        with:
          deno-version: v1.29.4

      - name: Generate Lume Static Site
        run: /opt/hostedtoolcache/deno/1.29.4/x64/deno task lume:build
        env:
          PROJECT: ${{ vars.PROJECT }}
          DOMAIN: ${{ vars.DOMAIN }}
          DIRECTUS_API_URL: ${{ vars.DIRECTUS_API_URL }}
          DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: rethinkcode
          entrypoint: main.ts
          root: ./
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
