name: Publish on Deno Deploy

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types:
      - webhook

env:
  DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
  DOMAIN: ${{ var.DOMAIN }}
  PROJECT: ${{ var.PROJECT }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.29.4

      - name: Build site
        run: deno task lume:build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: project-name
          import-map: "./import_map.json"
          entrypoint: main.ts
