name: Build Static with Lume

on:
  push:
    paths:
      - _src/**
      - .github/workflows/lume.yml
      - _config.ts
  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Cache Deno directories
        uses: actions/cache@v3
        id: deno-cache
        with:
          path: |
            /opt/hostedtoolcache/deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock') }}

      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        if: steps.deno-cache.outputs.cache-hit != 'true'
        with:
          deno-version: v1.29.4

      - name: Build site
        run: /opt/hostedtoolcache/deno/1.29.4/x64/deno task lume:build
        env:
          PROJECT: ${{ vars.PROJECT }}
          DOMAIN: ${{ vars.DOMAIN }}
          DIRECTUS_API_URL: ${{ vars.DIRECTUS_API_URL }}
          DIRECTUS_API_KEY: ${{ secrets.DIRECTUS_API_KEY }}

      - name: Commit and Push Static
        run: |
          git config --local user.name "Github Actions"
          git config --local user.email "github-actions@rethinkcode.org"
          git add static
          git commit -m "Automated commit of static files"
          git push
